# Site settings
title: Dony Purnama - Web Developer
header-img: img/home-bg.jpg
email: dony.purnama@gmail.com
copyright_name: donypurnama/Project/bits
description: "I'm Dony Purnama, a web designer, developer, and writer. More about me and my work below!!"
baseurl: "/startbootstrap-clean-blog-jekyll"
url: "http://yourdomain.com"
twitter_username: donypurnama
github_username:  donypurnama
facebook_username:  http://facebook.com/donypurnama
email_username:  dony.purnama@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
